# Generated by Django 5.0.3 on 2024-05-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='foto',
            field=models.ImageField(blank=True, default='NO IMAGE', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
