# Generated by Django 5.0.3 on 2024-06-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='foto',
            field=models.ImageField(blank=True, height_field='heigth', null=True, upload_to='photos/%Y/%m/%d/', width_field='width'),
        ),
    ]
