# Generated by Django 5.0.3 on 2024-06-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_product_options_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slag',
            field=models.SlugField(max_length=64, null=True, unique=True, verbose_name='URL'),
        ),
    ]
